# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sprusr
description: > # this means to ignore newlines until "baseurl:"
  super user of the realm of the internet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spru.sr" # the base hostname & protocol for your site
twitter_username: sprusr
github_username:  sprusr
linkedin_username:  streets

# Build settings
markdown: kramdown
