# Site settings
title: Scott Street - sprusr
description: "Real life wizard and Internet person"
keywords: "Scott Street,sprusr,scottystreet,ThroneRoom,Hakke,Muki.js,AstonHack,Aston"
author: "Scott Street"
baseurl: ""
url: "https://spru.sr"
favicon: /img/favicon.ico
permalink: pretty

# Content
links:
  - title: Blog
    url: /blog
  - title: Twitter
    url: https://twitter.com/sprusr
  - title: GitHub
    url: https://github.com/sprusr
  - title: Email
    url: mailto:scott@spru.sr
projects:
  - title: Muki.js
    description: >
      I got to play with one of [these cool mugs](http://pauligmuki.com/) at a
      hackathon. It has an e-ink display, powered by the heat of the liquid
      inside! Their existing developer libraries were for Android and iOS, so I
      reverse engineered the mug and implemented their Bluetooth API in
      javascript!
    image: /img/muki.png
    url: https://github.com/sprusr/muki.js
  - title: vpncmd.js
    description: >
      I got interested in setting up and maintaining my own VPN server, and what
      better way to manage such a thing than with javascript! And because it
      (pretty much) didn't already exist, I wrote a module for controlling a
      SoftEther VPN server.
    image: /img/vpncmd.png
    url: https://github.com/sprusr/vpncmd.js
  - title: Don't Laugh
    description: >
      A really stupid, and yet incredible hackathon project in the form of a
      game. A camera and elastic band shooting robot move back and forth - if
      you laugh or even smile, you get shot!
    image: /img/dontlaugh.png
    url: https://devpost.com/software/don-t-laugh
  - title: trel
    description: >
      After a combination of starting to use Trello a lot at work, and begining
      to want to switch my toolset to the terminal, I made a cute little command
      line client for Trello, written in javascript.
    image: /img/trel.png
    url: https://github.com/sprusr/trel
hackathons:
  - title: Local Hack Day II
  - title: BrumHack III
  - title: AstonHack 2015
  - title: GreatUniHack 2015
  - title: HackKings 2.0
  - title: HackCambridge
  - title: BanterHack
  - title: Hack@Brookes
  - title: HackUPC Spring 2016
  - title: HackLondon
  - title: StudentHack IV
  - title: BrumHack 4
  - title: HackSussex
  - title: AnvilHack II
  - title: MLH Prime
  - title: HackUPC Fall 2016
  - title: HackSheffield
  - title: Hackference
  - title: BrumHack 5
  - title: AstonHack 2016
  - title: GreatUniHack 2016
  - title: OxfordHack
  - title: Junction 2016
  - title: Local Hack Day III
  - title: Porticode
  - title: Hack the Holidays 2
  - title: HackUPC Winter 2017
  - title: BullHacks
  - title: Hack24 2017
  - title: HackCity
  - title: AnvilHack III
  - title: UKGovHack 2017
  - title: HackTheMidlands 2017

# Build settings
markdown: kramdown
